import type { CrossRule } from './types';

/** Règles croisées entre 2 piliers (porté intégralement de AN_RULES de bilan.html) */
export const AN_RULES: CrossRule[] = [
  { a: 'vision', sa: 'f', b: 'fit', sb: 'f', t1: "L'entreprise cherche encore son cap et son marché simultanément.", t2: "Clarifier le positionnement est probablement la priorité absolue avant d'accélérer." },
  { a: 'vision', sa: 'f', b: 'finance', sb: 'f', t1: 'Le manque de direction fragilise aussi les décisions financières.', t2: "L'entreprise risque de fonctionner principalement dans l'urgence." },
  { a: 'vision', sa: 'f', b: 'okr', sb: 'f', t1: "L'absence de cap impacte directement l'organisation et l'exécution.", t2: 'Les équipes ont du mal à prioriser faute de direction claire.' },
  { a: 'vision', sa: 'f', b: 'team', sb: 'f', t1: "Le manque de vision partagée fragilise l'engagement collectif.", t2: "L'équipe manque de repères communs pour avancer ensemble." },
  { a: 'vision', sa: 'f', b: 'fit', sb: 'c', t1: "L'offre se construit mais sans cap stratégique clairement défini.", t2: "Valider un marché sans savoir où l'on veut aller expose à des pivots coûteux." },
  { a: 'vision', sa: 'f', b: 'finance', sb: 'c', t1: "L'activité progresse financièrement mais sans direction affirmée.", t2: 'Piloter durablement sera difficile sans cap défini.' },
  { a: 'vision', sa: 'f', b: 'okr', sb: 'c', t1: "L'exécution se structure mais sans vision pour la guider.", t2: 'Les efforts risquent de manquer de cohérence à long terme.' },
  { a: 'vision', sa: 'f', b: 'team', sb: 'c', t1: "L'équipe se construit mais manque d'un projet commun pour s'aligner.", t2: 'La cohésion reste fragile sans direction partagée.' },
  { a: 'vision', sa: 'f', b: 'fit', sb: 's', t1: "L'offre fonctionne mieux que la structuration globale de l'entreprise.", t2: 'Le risque est de subir la croissance plutôt que de la piloter.' },
  { a: 'vision', sa: 'f', b: 'finance', sb: 's', t1: "L'entreprise est financièrement stable mais sans direction claire.", t2: 'Le risque est de maintenir une activité rentable sans trajectoire.' },
  { a: 'vision', sa: 'f', b: 'okr', sb: 's', t1: "L'équipe exécute efficacement mais sans vision long terme.", t2: "Le risque est l'épuisement ou la dispersion stratégique." },
  { a: 'vision', sa: 'f', b: 'team', sb: 's', t1: "Le collectif est solide malgré un manque de cap structuré.", t2: "L'humain soutient l'entreprise plus que la stratégie en ce moment." },
  { a: 'vision', sa: 'c', b: 'fit', sb: 'f', t1: "La vision se construit mais l'offre n'est pas encore validée.", t2: "Tester rapidement le marché permettra d'ancrer la direction." },
  { a: 'vision', sa: 'c', b: 'finance', sb: 'f', t1: 'La direction se précise mais le modèle économique reste fragile.', t2: 'Structurer le pilotage financier en parallèle de la vision est urgent.' },
  { a: 'vision', sa: 'c', b: 'okr', sb: 'f', t1: "Le cap se dessine mais l'exécution manque de structure.", t2: 'Formaliser les priorités permettra d\'incarner la vision en actions.' },
  { a: 'vision', sa: 'c', b: 'team', sb: 'f', t1: "La direction émerge mais l'équipe n'est pas encore pleinement embarquée.", t2: "L'alignement collectif est le prochain défi clé." },
  { a: 'vision', sa: 'c', b: 'fit', sb: 'c', t1: "L'entreprise construit progressivement sa direction et son positionnement.", t2: "Une phase normale de structuration — l'enjeu est de tenir le rythme." },
  { a: 'vision', sa: 'c', b: 'finance', sb: 'c', t1: 'Le projet progresse mais plusieurs fondations restent à consolider.', t2: "Transformer l'intuition en pilotage durable est le défi du moment." },
  { a: 'vision', sa: 'c', b: 'okr', sb: 'c', t1: "L'entreprise avance mais manque encore d'un cadre totalement stabilisé.", t2: 'Les priorités existent mais gagneraient à être davantage incarnées.' },
  { a: 'vision', sa: 'c', b: 'team', sb: 'c', t1: 'Le collectif et la direction se construisent ensemble.', t2: "L'alignement humain dépend encore beaucoup du quotidien." },
  { a: 'vision', sa: 'c', b: 'fit', sb: 's', t1: 'Le marché est validé — la vision doit maintenant se préciser pour capitaliser.', t2: "C'est le bon moment pour formaliser un cap clair et ambitieux." },
  { a: 'vision', sa: 'c', b: 'finance', sb: 's', t1: "La solidité financière est là — la vision doit s'affirmer pour lui donner une trajectoire.", t2: "L'entreprise a les moyens de ses ambitions, il faut les clarifier." },
  { a: 'vision', sa: 'c', b: 'okr', sb: 's', t1: "L'exécution est solide — une vision plus affirmée lui donnerait encore plus d'impact.", t2: "C'est le bon moment pour amplifier les efforts en clarifiant le cap." },
  { a: 'vision', sa: 'c', b: 'team', sb: 's', t1: "L'équipe est solide — une vision plus affirmée lui permettrait de se dépasser.", t2: "Le collectif est prêt à s'aligner sur un projet plus ambitieux." },
  { a: 'vision', sa: 's', b: 'fit', sb: 'f', t1: "La direction est claire mais l'offre n'est pas encore suffisamment validée.", t2: "L'adéquation réelle avec le marché est désormais l'enjeu principal." },
  { a: 'vision', sa: 's', b: 'finance', sb: 'f', t1: "L'ambition est claire mais le modèle économique reste fragile.", t2: 'La croissance pourrait être freinée par le manque de solidité financière.' },
  { a: 'vision', sa: 's', b: 'okr', sb: 'f', t1: "La stratégie est définie mais l'exécution manque de structure.", t2: 'Le défi principal est organisationnel.' },
  { a: 'vision', sa: 's', b: 'team', sb: 'f', t1: "Le cap est clair mais l'adhésion collective reste fragile.", t2: 'Le risque principal est humain plutôt que stratégique.' },
  { a: 'vision', sa: 's', b: 'fit', sb: 'c', t1: 'La vision est solide — il faut accélérer la validation marché.', t2: 'Transformer la clarté stratégique en traction commerciale réelle est l\'enjeu.' },
  { a: 'vision', sa: 's', b: 'finance', sb: 'c', t1: 'Le cap est défini — le modèle économique doit se consolider.', t2: 'Structurer le pilotage financier sécurisera la trajectoire.' },
  { a: 'vision', sa: 's', b: 'okr', sb: 'c', t1: "La vision est là — l'exécution se structure progressivement.", t2: 'Continuer à incarner la stratégie dans des objectifs mesurables.' },
  { a: 'vision', sa: 's', b: 'team', sb: 'c', t1: "Le cap est défini — l'équipe est en train de s'aligner.", t2: "Investir dans l'alignement collectif amplifiera l'impact de la vision." },
  { a: 'vision', sa: 's', b: 'fit', sb: 's', t1: 'Positionnement cohérent et direction claire — une combinaison solide.', t2: 'Les bases stratégiques paraissent bien établies.' },
  { a: 'vision', sa: 's', b: 'finance', sb: 's', t1: 'Direction et pilotage financier semblent alignés.', t2: "L'entreprise est structurée pour soutenir une croissance durable." },
  { a: 'vision', sa: 's', b: 'okr', sb: 's', t1: 'Vision et exécution semblent efficacement alignées.', t2: 'La capacité de transformation paraît forte.' },
  { a: 'vision', sa: 's', b: 'team', sb: 's', t1: 'Le collectif avance autour d\'un projet clair et fédérateur.', t2: "L'alignement humain et stratégique paraît solide." },
  { a: 'fit', sa: 'f', b: 'finance', sb: 'f', t1: "L'entreprise cherche encore un modèle réellement viable.", t2: 'Le manque de traction impacte directement les résultats financiers.' },
  { a: 'fit', sa: 'f', b: 'okr', sb: 'f', t1: "Les efforts d'exécution manquent d'impact faute de validation marché.", t2: "Le risque est d'optimiser une offre encore insuffisamment validée." },
  { a: 'fit', sa: 'f', b: 'team', sb: 'f', t1: "Les difficultés marché fragilisent l'engagement de l'équipe.", t2: 'Le manque de résultats visibles peut créer de la fatigue collective.' },
  { a: 'fit', sa: 'f', b: 'finance', sb: 'c', t1: 'La traction manque encore mais le pilotage financier progresse.', t2: 'Trouver le bon marché avant que les ressources ne s\'épuisent est la priorité.' },
  { a: 'fit', sa: 'f', b: 'okr', sb: 'c', t1: "L'exécution se structure mais l'offre n'est pas encore validée.", t2: 'Risque d\'optimiser une machine bien huilée qui ne va pas dans la bonne direction.' },
  { a: 'fit', sa: 'f', b: 'team', sb: 'c', t1: "L'équipe progresse mais peine à trouver sa traction marché.", t2: 'La motivation collective dépendra de plus en plus de résultats tangibles.' },
  { a: 'fit', sa: 'f', b: 'finance', sb: 's', t1: "La structure financière est solide mais l'offre ne convainc pas encore.", t2: "Les ressources sont là — l'enjeu est de trouver le bon positionnement." },
  { a: 'fit', sa: 'f', b: 'okr', sb: 's', t1: "L'exécution est excellente mais au service d'une offre mal validée.", t2: "Il faut challenger l'offre avant d'optimiser davantage l'organisation." },
  { a: 'fit', sa: 'f', b: 'team', sb: 's', t1: "L'équipe est forte mais l'offre ne rencontre pas encore son marché.", t2: 'Le collectif est une vraie force — à mobiliser sur la validation marché.' },
  { a: 'fit', sa: 'c', b: 'finance', sb: 'f', t1: "L'offre se construit mais le modèle économique reste fragile.", t2: 'Valider vite pour sécuriser les ressources avant qu\'elles ne manquent.' },
  { a: 'fit', sa: 'c', b: 'okr', sb: 'f', t1: "L'offre progresse mais sans structure d'exécution pour l'exploiter.", t2: "Mettre en place des rituels d'exécution accélérera la validation." },
  { a: 'fit', sa: 'c', b: 'team', sb: 'f', t1: "L'offre se construit mais l'équipe manque de cohésion pour aller vite.", t2: 'Renforcer le collectif est un levier direct pour accélérer la validation.' },
  { a: 'fit', sa: 'c', b: 'finance', sb: 'c', t1: "L'offre et le modèle économique se construisent ensemble.", t2: "Phase normale — l'enjeu est de valider vite pour sécuriser le modèle." },
  { a: 'fit', sa: 'c', b: 'okr', sb: 'c', t1: "L'offre et l'exécution progressent mais restent à stabiliser.", t2: "Continuer à itérer rapidement pour ancrer l'offre et les priorités." },
  { a: 'fit', sa: 'c', b: 'team', sb: 'c', t1: "L'offre et l'équipe se construisent en parallèle.", t2: 'Dynamique saine — veiller à ce que les deux s\'alimentent mutuellement.' },
  { a: 'fit', sa: 'c', b: 'finance', sb: 's', t1: 'La solidité financière donne du temps pour finaliser la validation marché.', t2: 'Position confortable — en profiter pour itérer sans pression excessive.' },
  { a: 'fit', sa: 'c', b: 'okr', sb: 's', t1: "L'exécution est solide — elle doit s'ajuster à l'évolution de l'offre.", t2: 'Garder la flexibilité nécessaire pour pivoter si le marché le demande.' },
  { a: 'fit', sa: 'c', b: 'team', sb: 's', t1: "L'équipe est solide et accompagne la validation de l'offre.", t2: 'Bonne dynamique — capitaliser sur la force collective pour accélérer.' },
  { a: 'fit', sa: 's', b: 'finance', sb: 'f', t1: 'Le potentiel commercial est réel mais la structure économique reste fragile.', t2: 'Transformer la traction en rentabilité est l\'enjeu immédiat.' },
  { a: 'fit', sa: 's', b: 'okr', sb: 'f', t1: "Le marché répond présent mais l'organisation ne suit pas encore.", t2: "Le risque est de perdre des opportunités faute d'exécution." },
  { a: 'fit', sa: 's', b: 'team', sb: 'f', t1: "L'offre fonctionne mais les tensions internes peuvent freiner la croissance.", t2: 'Le défi principal est désormais humain et organisationnel.' },
  { a: 'fit', sa: 's', b: 'finance', sb: 'c', t1: 'La traction est là — le modèle économique doit se consolider.', t2: 'Structurer la rentabilité permettra de pérenniser la croissance.' },
  { a: 'fit', sa: 's', b: 'okr', sb: 'c', t1: "L'offre est validée — l'exécution doit maintenant monter en puissance.", t2: 'Structurer les priorités permettra d\'exploiter pleinement le potentiel.' },
  { a: 'fit', sa: 's', b: 'team', sb: 'c', t1: "Le marché répond — l'équipe doit s'organiser pour scaler.", t2: "Investir dans l'organisation collective est le levier clé du moment." },
  { a: 'fit', sa: 's', b: 'finance', sb: 's', t1: 'Offre validée et modèle économique solide — belle base de croissance.', t2: "L'entreprise semble prête à accélérer sereinement." },
  { a: 'fit', sa: 's', b: 'okr', sb: 's', t1: "L'offre est validée et l'exécution est au rendez-vous.", t2: "L'entreprise semble avoir trouvé son rythme de croisière." },
  { a: 'fit', sa: 's', b: 'team', sb: 's', t1: "L'offre fonctionne et l'équipe est solide — une combinaison gagnante.", t2: 'Excellentes bases pour une croissance durable.' },
  { a: 'finance', sa: 'f', b: 'okr', sb: 'f', t1: 'Le manque de pilotage fragilise la stabilité globale.', t2: "L'entreprise a du mal à transformer ses efforts en résultats durables." },
  { a: 'finance', sa: 'f', b: 'team', sb: 'f', t1: "Les tensions financières impactent directement l'énergie de l'équipe.", t2: 'Le contexte génère de l\'incertitude et de la fatigue collective.' },
  { a: 'finance', sa: 'f', b: 'okr', sb: 'c', t1: "Le pilotage s'améliore mais ne suffit pas encore à stabiliser les finances.", t2: "Structurer l'exécution tout en cherchant un levier de rentabilité." },
  { a: 'finance', sa: 'f', b: 'team', sb: 'c', t1: "L'équipe progresse malgré un contexte financier difficile.", t2: 'La motivation collective est précieuse — ne pas la laisser s\'éroder.' },
  { a: 'finance', sa: 'f', b: 'okr', sb: 's', t1: "L'exécution est solide mais les fondations financières restent fragiles.", t2: "Mettre la puissance d'exécution au service de la rentabilité est urgent." },
  { a: 'finance', sa: 'f', b: 'team', sb: 's', t1: "L'équipe est forte malgré des difficultés financières.", t2: 'La solidité collective est un atout précieux pour traverser cette phase.' },
  { a: 'finance', sa: 'c', b: 'okr', sb: 'c', t1: "Le pilotage financier et l'exécution progressent en parallèle.", t2: 'Dynamique positive — veiller à ce que les deux se renforcent mutuellement.' },
  { a: 'finance', sa: 'c', b: 'team', sb: 'c', t1: "Le modèle économique et l'équipe se construisent ensemble.", t2: 'Phase de structuration — maintenir l\'élan et la cohésion.' },
  { a: 'finance', sa: 'c', b: 'okr', sb: 's', t1: "L'exécution est solide — elle doit s'appuyer sur un pilotage financier plus robuste.", t2: 'Structurer les indicateurs financiers sécurisera la performance.' },
  { a: 'finance', sa: 'c', b: 'team', sb: 's', t1: "L'équipe est solide malgré un modèle économique encore en construction.", t2: 'La force collective est un atout pour traverser cette phase de consolidation.' },
  { a: 'finance', sa: 's', b: 'okr', sb: 'f', t1: "L'entreprise est saine financièrement mais l'exécution limite le potentiel.", t2: "Le principal levier d'amélioration est organisationnel." },
  { a: 'finance', sa: 's', b: 'team', sb: 'f', t1: "La stabilité économique ne suffit pas encore à créer un collectif solide.", t2: "L'enjeu principal est désormais humain." },
  { a: 'finance', sa: 's', b: 'okr', sb: 'c', t1: "Les finances sont solides — l'exécution doit maintenant suivre.", t2: 'Structurer les priorités permettra de transformer la solidité en impact.' },
  { a: 'finance', sa: 's', b: 'team', sb: 'c', t1: "La santé financière est là — l'équipe monte progressivement en puissance.", t2: 'Continuer à investir dans le collectif amplifiera les résultats.' },
  { a: 'finance', sa: 's', b: 'okr', sb: 's', t1: 'Pilotage financier et exécution semblent bien alignés.', t2: "L'entreprise dispose d'une mécanique solide pour délivrer ses ambitions." },
  { a: 'finance', sa: 's', b: 'team', sb: 's', t1: "Solidité financière et cohésion d'équipe forment une base très solide.", t2: "L'entreprise a les moyens humains et économiques de ses ambitions." },
  { a: 'okr', sa: 'f', b: 'team', sb: 'f', t1: "Le manque de structure et d'alignement humain freine fortement l'entreprise.", t2: 'Le quotidien est probablement vécu comme réactif et désorganisé.' },
  { a: 'okr', sa: 'f', b: 'team', sb: 'c', t1: "L'équipe progresse mais sans cadre d'exécution suffisamment clair.", t2: "Structurer les priorités aiderait l'équipe à canaliser son énergie." },
  { a: 'okr', sa: 'f', b: 'team', sb: 's', t1: "L'équipe est solide mais manque de structure pour être pleinement efficace.", t2: 'Des rituels et objectifs clairs libéreraient le potentiel collectif.' },
  { a: 'okr', sa: 'c', b: 'team', sb: 'f', t1: "L'exécution se structure mais peine à embarquer l'équipe.", t2: "Associer l'équipe à la construction du cadre favorisera son adoption." },
  { a: 'okr', sa: 'c', b: 'team', sb: 'c', t1: "Exécution et cohésion d'équipe progressent en parallèle.", t2: 'Continuer à construire ensemble pour que les deux se renforcent.' },
  { a: 'okr', sa: 'c', b: 'team', sb: 's', t1: "L'équipe est solide et accompagne la montée en puissance de l'exécution.", t2: 'Dynamique très positive — capitaliser sur la force collective.' },
  { a: 'okr', sa: 's', b: 'team', sb: 'f', t1: "Les méthodes existent mais l'adhésion collective est insuffisante.", t2: 'Le défi n\'est pas technique mais humain.' },
  { a: 'okr', sa: 's', b: 'team', sb: 'c', t1: "L'exécution est solide — l'équipe monte progressivement en puissance.", t2: 'Continuer à investir dans le collectif pour amplifier les résultats.' },
  { a: 'okr', sa: 's', b: 'team', sb: 's', t1: "Exécution et cohésion d'équipe sont au rendez-vous.", t2: 'Organisation performante et collectif solide — une vraie force !' },
];
